// Eco-Insight Revenue OS — Seed Data
// Mutable in-memory store. Replace with Prisma/DB in production.
import type { User, Signal, Lead, Account, Opportunity, Task, Goal, Activity, Email, Meeting, QueueItem, AgentConfig } from './types';

// ── Team ─────────────────────────────────────────
export const USERS: User[] = [
  { id: 'u1', name: 'Juuso Kari', ini: 'JK', role: 'Commercial Director', ac: 'green' },
  { id: 'u2', name: 'Laura Puranen', ini: 'LP', role: 'CEO', ac: 'default' },
  { id: 'u3', name: 'Nick Schoch', ini: 'NS', role: 'COO', ac: 'blue' },
];
export const ME = USERS[0];

// ── Signals ──────────────────────────────────────
export let signals: Signal[] = [
  { id:'s1',type:'ppa_announcement',title:'Ørsted signs 15-year corporate PPA with BASF for 186 MW offshore wind',src:'Reuters Energy',srcUrl:'https://reuters.com/energy/orsted-basf-ppa',at:'2026-03-11T08:20:00',sum:'BASF will receive GoOs as part of the agreement. Both parties likely need certificate management tooling.',rel:92,conf:'high',why:'Direct GoO involvement in PPA structure. BASF is an industrial buyer with likely manual cert processes.',status:'new',agent:'Signal Hunter' },
  { id:'s2',type:'renewable_target',title:'Iberdrola raises 2030 renewable target to 100 GW globally',src:'Bloomberg Green',srcUrl:'https://bloomberg.com/iberdrola-target',at:'2026-03-10T15:40:00',sum:'Expanded target implies massive certificate volume increase across EECS and I-REC schemes.',rel:85,conf:'high',why:'Scale of target creates significant certificate management burden across multiple schemes.',status:'new',agent:'Signal Hunter' },
  { id:'s3',type:'job_posting',title:'Uniper hiring "GoO Trading Analyst" — Düsseldorf',src:'LinkedIn Jobs',srcUrl:'https://linkedin.com/jobs/uniper-goo',at:'2026-03-10T12:00:00',sum:'New GoO-specific hire suggests scaling certificate trading operations. Possible greenfield opportunity.',rel:78,conf:'medium',why:'GoO-specific role suggests growing operations. New hires often trigger tool evaluation.',status:'new',agent:'Signal Hunter' },
  { id:'s4',type:'market_entry',title:'TotalEnergies launches GoO desk for Scandinavian market',src:'Montel News',srcUrl:'https://montelnews.com/total-goo',at:'2026-03-09T09:15:00',sum:'New market entry into Nordics GoO trading. Will need registry connectivity and trading tools from day one.',rel:88,conf:'high',why:'Greenfield GoO desk in our core market. High urgency, no incumbent tooling.',status:'new',agent:'Signal Hunter' },
  { id:'s5',type:'conference',title:'Nordic Energy Certificates Summit — Oslo, May 12-13',src:'Event Detection',srcUrl:null,at:'2026-03-08T10:00:00',sum:'Key conference for GoO/ELcert market. Speaking opportunity detected.',rel:72,conf:'medium',why:'Networking and lead generation opportunity.',status:'reviewed',agent:'Signal Hunter' },
  { id:'s6',type:'registry_pain',title:'AIB registry downtime causes GoO settlement delays across 12 markets',src:'AIB Alert',srcUrl:'https://aib-net.org/alerts',at:'2026-03-07T14:30:00',sum:'Multi-market settlement failure highlights fragility of manual registry workflows.',rel:90,conf:'high',why:'Acute pain event affecting many target accounts. Creates urgency for automation.',status:'new',agent:'Signal Hunter' },
];

// ── Leads ────────────────────────────────────────
export let leads: Lead[] = [
  { id:'l1',company:'BASF SE',domain:'basf.com',src:'Signal',signalId:'s1',type:'Industrial',country:'Germany',region:'DACH',stage:'New',pain:'Likely manual GoO tracking for PPA volumes. No dedicated cert team visible.',fit:['GoO Procurement','Reporting'],scores:{f:72,i:65,u:75,a:30,c:80},conf:'medium',owner:USERS[0],createdAt:'2026-03-11' },
  { id:'l2',company:'Uniper SE',domain:'uniper.com',src:'Signal',signalId:'s3',type:'Utility',country:'Germany',region:'DACH',stage:'Researching',pain:'Expanding GoO trading desk. Currently hiring analyst. Likely outgrowing manual tools.',fit:['GoO Trading','GoO Issuance'],scores:{f:80,i:60,u:70,a:35,c:75},conf:'medium',owner:USERS[0],createdAt:'2026-03-10' },
  { id:'l3',company:'TotalEnergies Trading',domain:'totalenergies.com',src:'Signal',signalId:'s4',type:'Trader',country:'France',region:'Western Europe',stage:'Qualified',pain:'New GoO desk for Nordics — greenfield. Needs full stack from day one.',fit:['GoO Trading','GoO Issuance','Reporting','API Integration'],scores:{f:90,i:85,u:88,a:45,c:85},conf:'high',owner:USERS[1],createdAt:'2026-03-09' },
  { id:'l4',company:'Enel Green Power',domain:'enelgreenpower.com',src:'Conference',signalId:null,type:'Utility',country:'Italy',region:'Southern Europe',stage:'New',pain:'60 GW renewable capacity globally. Custom internal registry. Scale problem.',fit:['GoO Issuance','Reporting'],scores:{f:65,i:35,u:55,a:25,c:90},conf:'low',owner:USERS[2],createdAt:'2026-03-05' },
];

// ── Accounts ─────────────────────────────────────
export let accounts: Account[] = [
  { id:'a1',name:'Vattenfall Nordic AB',type:'Utility',country:'Sweden',cc:'SE',region:'Nordics',status:'Active',schemes:['GoO','ELcert'],scores:{f:92,i:70,u:82,a:75,c:88},owner:USERS[0],pipe:380000,lastAct:'2026-02-19',pain:'Manual GoO reconciliation consuming 3+ FTE. Grexel + Excel workflows cannot scale.',whyNow:'Budget cycle Q2. Champion Lars actively evaluating. Procurement needs 3 vendor quotes.',fit:['GoO Issuance','GoO Trading','Reporting'],aiConf:0.85,competitors:'Grexel (incumbent), CMO (shortlisted), Bloomberg TOMS (considered)',contacts:[{id:'c1',name:'Lars Eriksson',title:'Head of GoO Desk',role:'Champion',warmth:'Warm',email:'lars.eriksson@vattenfall.com',phone:'+46 8 739 5000'},{id:'c2',name:'Helena Strand',title:'VP Energy Markets',role:'Economic Buyer',warmth:'Cold',email:'helena.strand@vattenfall.com'}] },
  { id:'a2',name:'Fortum Power and Heat',type:'Utility',country:'Finland',cc:'FI',region:'Nordics',status:'Active',schemes:['GoO','I-REC'],scores:{f:85,i:55,u:75,a:60,c:70},owner:USERS[1],pipe:145000,lastAct:'2026-03-09',pain:'Manual I-REC and GoO issuance via Fingrid. 2-person team spending 3 days/month on reconciliation.',whyNow:'CFO budget cycle in Q2. Anna driving but needs executive sponsor.',fit:['I-REC Registry','GoO Issuance'],aiConf:0.65,contacts:[{id:'c3',name:'Anna Bergström',title:'Certificate Operations Manager',role:'Champion',warmth:'Warm',email:'anna.bergstrom@fortum.com'},{id:'c4',name:'Annika Virtanen',title:'CFO — Energy Products',role:'Economic Buyer',warmth:'Cold',email:'annika.virtanen@fortum.com'}] },
  { id:'a3',name:'E.ON Energy Markets',type:'Retailer',country:'Germany',cc:'DE',region:'DACH',status:'Active',schemes:['GoO','REGO'],scores:{f:88,i:82,u:88,a:70,c:92},owner:USERS[0],pipe:460000,lastAct:'2026-03-08',pain:'SAP + Excel cert management for B2C green tariffs. Evaluating 3 vendors.',whyNow:'Active vendor evaluation. Kai is champion but IT team needs API validation.',fit:['GoO Procurement','Reporting','ERP Integration'],aiConf:0.85,contacts:[{id:'c5',name:'Kai Mueller',title:'Head of Energy Markets',role:'Champion',warmth:'Warm',email:'kai.mueller@eon.com'},{id:'c6',name:'Thomas Weber',title:'IT Director',role:'Technical Buyer',warmth:'Cold',email:'thomas.weber@eon.com'}] },
  { id:'a4',name:'Statkraft Markets',type:'Trader',country:'Norway',cc:'NO',region:'Nordics',status:'Active',schemes:['GoO','ELcert'],scores:{f:90,i:60,u:70,a:55,c:85},owner:USERS[0],pipe:290000,lastAct:'2026-03-07',pain:'Bloomberg TOMS + proprietary cert tracking (5 years old). 4 FTE on manual GoO work.',whyNow:'Referral via Axpo. Pilot concept resonated with Torben.',fit:['GoO Trading','GoO Issuance','API Integration'],aiConf:0.65,contacts:[{id:'c7',name:'Torben Rasmussen',title:'VP Renewable Trading',role:'Economic Buyer',warmth:'Cold',email:'torben.rasmussen@statkraft.com'}] },
  { id:'a5',name:'Axpo Nordic AS',type:'Trader',country:'Norway',cc:'NO',region:'Nordics',status:'Partner',schemes:['GoO','ELcert','REGO'],scores:{f:95,i:40,u:55,a:92,c:80},owner:USERS[0],pipe:95000,lastAct:'2026-03-10',pain:'Live customer. Expanding to ELcert module.',whyNow:'QBR March 28. Expansion pricing negotiation active.',fit:['ELcert Module','API Integration'],aiConf:0.90,contacts:[{id:'c8',name:'Erik Sandvik',title:'Head of Certificate Trading',role:'Champion',warmth:'Strong',email:'erik.sandvik@axpo.com'}] },
  { id:'a6',name:'RWE Renewables Europe',type:'Utility',country:'Germany',cc:'DE',region:'DACH',status:'Prospect',schemes:['GoO'],scores:{f:82,i:40,u:45,a:30,c:90},owner:USERS[1],pipe:320000,lastAct:'2026-03-05',pain:'50 GW renewable capacity. Unknown current tooling.',whyNow:'Discovery call March 20. Maria connected via LinkedIn.',fit:['GoO Issuance','Reporting'],aiConf:0.3,contacts:[{id:'c9',name:'Maria Hoffmann',title:'Head of Certificates',role:'Champion',warmth:'Cold',email:'maria.hoffmann@rwe.com'}] },
];

// ── Opportunities ────────────────────────────────
export let opps: Opportunity[] = [
  { id:'o1',name:'Vattenfall GoO Platform',accId:'a1',accName:'Vattenfall Nordic AB',stage:'Proposal',amt:380000,prob:65,close:'2026-06-30',owner:USERS[0],health:{eng:40,stake:75,comp:60,time:50},next:'Follow up on revised GoO volume proposal',nextDate:'2026-03-15' },
  { id:'o2',name:'E.ON Germany GoO Procurement',accId:'a3',accName:'E.ON Energy Markets',stage:'Solution Fit',amt:460000,prob:50,close:'2026-05-31',owner:USERS[0],health:{eng:65,stake:55,comp:40,time:60},next:'Follow up with Kai on API feasibility',nextDate:'2026-03-14' },
  { id:'o3',name:'Statkraft GoO Trading Pilot',accId:'a4',accName:'Statkraft Markets',stage:'Qualified',amt:290000,prob:35,close:'2026-07-31',owner:USERS[0],health:{eng:30,stake:35,comp:70,time:80},next:'Prepare pilot scope via Erik Sandvik referral',nextDate:'2026-03-18' },
  { id:'o4',name:'Fortum I-REC Pilot',accId:'a2',accName:'Fortum Power and Heat',stage:'Discovery',amt:145000,prob:20,close:'2026-09-30',owner:USERS[1],health:{eng:55,stake:40,comp:80,time:70},next:'Send platform overview ahead of call',nextDate:'2026-03-12' },
  { id:'o5',name:'E.ON UK REGO Module',accId:'a3',accName:'E.ON Next UK',stage:'Proposal',amt:185000,prob:65,close:'2026-04-30',owner:USERS[1],health:{eng:80,stake:70,comp:65,time:75},next:'Proposal review call with Sarah Hughes',nextDate:'2026-03-25' },
  { id:'o6',name:'Axpo ELcert Expansion',accId:'a5',accName:'Axpo Nordic AS',stage:'Negotiation',amt:95000,prob:80,close:'2026-03-31',owner:USERS[0],health:{eng:90,stake:85,comp:95,time:60},next:'Send revised pricing — 8.5% discount',nextDate:'2026-03-20' },
  { id:'o7',name:'RWE GoO Issuance',accId:'a6',accName:'RWE Renewables Europe',stage:'Contacted',amt:320000,prob:10,close:'2026-12-31',owner:USERS[1],health:{eng:20,stake:25,comp:80,time:90},next:'Discovery call March 20',nextDate:'2026-03-20' },
];

// ── Tasks ────────────────────────────────────────
export let tasks: Task[] = [
  { id:'t1',title:'Follow up Vattenfall — GoO proposal response',accName:'Vattenfall Nordic AB',accId:'a1',due:'2026-03-10',owner:USERS[0],assignees:[USERS[0]],pri:'High',status:'Open',src:'Pipeline Hygiene Agent',goalId:'g1',comments:[{by:USERS[1],text:'Lars was responsive last week — try calling directly',at:'2026-03-09T14:00:00'}] },
  { id:'t2',title:'Prepare Statkraft pilot scope document',accName:'Statkraft Markets',accId:'a4',due:'2026-03-18',owner:USERS[0],assignees:[USERS[0],USERS[2]],pri:'High',status:'In Progress',src:'Meeting Notes',goalId:'g2',reviewer:USERS[1],comments:[] },
  { id:'t3',title:'Send Fortum platform overview',accName:'Fortum Power and Heat',accId:'a2',due:'2026-03-12',owner:USERS[1],assignees:[USERS[1]],pri:'High',status:'Open',src:'Manual',comments:[] },
  { id:'t4',title:'Follow up Kai Mueller — API feasibility',accName:'E.ON Energy Markets',accId:'a3',due:'2026-03-08',owner:USERS[0],assignees:[USERS[0]],pri:'High',status:'Open',src:'AI Suggested',comments:[{by:USERS[2],text:'@Juuso — Kai mentioned SSO concern in last call. Address in follow-up.',at:'2026-03-08T09:00:00',mentions:['u1']}] },
  { id:'t5',title:'Send Axpo revised pricing — ELcert',accName:'Axpo Nordic AS',accId:'a5',due:'2026-03-20',owner:USERS[0],assignees:[USERS[0]],pri:'Medium',status:'Open',src:'Manual',goalId:'g3',comments:[] },
  { id:'t6',title:'Review 3 new signals',accName:'',accId:'',due:'2026-03-11',owner:USERS[0],assignees:[USERS[0],USERS[1]],pri:'Medium',status:'Open',src:'Signal Hunter Agent',comments:[] },
];

// ── Goals ────────────────────────────────────────
export let goals: Goal[] = [
  { id:'g1',title:'Close Vattenfall GoO Platform',accName:'Vattenfall Nordic AB',accId:'a1',owner:USERS[0],status:'active' },
  { id:'g2',title:'Launch Statkraft Pilot',accName:'Statkraft Markets',accId:'a4',owner:USERS[0],status:'active' },
  { id:'g3',title:'Expand Axpo ELcert',accName:'Axpo Nordic AS',accId:'a5',owner:USERS[0],status:'active' },
];

// ── Activities ───────────────────────────────────
export let activities: Activity[] = [
  { id:'x1',type:'Email',date:'2026-03-10T09:14:00',accId:'a5',accName:'Axpo Nordic AS',sum:'ELcert module pricing — revised offer sent',detail:'Sent 8.5% multi-module discount proposal. Awaiting Erik\'s sign-off.',who:USERS[0],src:'Outlook Sync' },
  { id:'x2',type:'Meeting',date:'2026-03-09T14:00:00',accId:'a2',accName:'Fortum Power and Heat',sum:'Discovery call — Fortum I-REC registry needs',detail:'Anna confirmed interest. Key concern: CFO approval needed.',who:USERS[1],src:'Calendar Sync' },
  { id:'x3',type:'Email',date:'2026-03-08T16:30:00',accId:'a3',accName:'E.ON Energy Markets',sum:'API integration feasibility — follow-up sent',detail:'Sent SAP connector documentation. Awaiting IT team review.',who:USERS[0],src:'Outlook Sync' },
  { id:'x4',type:'Meeting',date:'2026-03-07T10:00:00',accId:'a4',accName:'Statkraft Markets',sum:'Intro call via Erik Sandvik referral',detail:'Good intro. Torben aware of Eco-Insight via Axpo. Pilot concept resonated.',who:USERS[0],src:'Calendar Sync' },
  { id:'x5',type:'Email',date:'2026-02-28T11:00:00',accId:'a3',accName:'E.ON Energy Markets',sum:'Commercial proposal sent — E.ON Germany',detail:'Full proposal submitted. €460K ARR, 3-year term.',who:USERS[0],src:'Outlook Sync' },
  { id:'x6',type:'Note',date:'2026-02-19T09:00:00',accId:'a1',accName:'Vattenfall Nordic AB',sum:'Revised GoO volume proposal sent',detail:'Updated commercial terms with volume thresholds. No response yet.',who:USERS[0],src:'Manual' },
];

// ── Queue ────────────────────────────────────────
export let queue: QueueItem[] = [
  { id:'q1',type:'outreach_draft',title:'Cold outreach to BASF SE — GoO Procurement',accName:'BASF SE',accId:null,agent:'Outreach Drafter',conf:0.82,confBreak:{relevance:0.92,personalization:0.74,timing:0.81},reasoning:'BASF appeared in PPA signal with Ørsted. Industrial buyer profile matches ICP. No prior contact — cold outreach via LinkedIn-sourced contact.',sources:[{name:'Reuters Energy',url:'https://reuters.com/energy/orsted-basf-ppa'},{name:'LinkedIn',url:'https://linkedin.com/in/basf-energy'}],payload:{to:'Michael Braun <m.braun@basf.com>',subject:'Eco-Insight — GoO certificate management for BASF',body:'Hi Michael,\n\nI noticed BASF recently signed a 186 MW offshore wind PPA with Ørsted. Agreements of this scale typically involve significant GoO certificate volumes.\n\nWould you be open to a brief conversation about how we help companies like yours automate GoO management?\n\nBest,\nJuuso Kari'},status:'pending',pri:'Normal',createdAt:'2026-03-11T09:30:00' },
  { id:'q2',type:'lead_qualification',title:'Qualify Uniper SE as GoO Trading lead',accName:'Uniper SE',accId:null,agent:'Lead Qualifier',conf:0.71,confBreak:{icp_fit:0.80,intent:0.65,entity_match:0.68},reasoning:'Uniper hiring GoO Trading Analyst. Signal confidence is medium because job posting doesn\'t confirm tool evaluation.',sources:[{name:'LinkedIn Jobs',url:'https://linkedin.com/jobs/uniper-goo'}],payload:{company:'Uniper SE',type:'Utility',country:'Germany',stage:'Researching',scores:{f:80,i:60,u:70,a:35,c:75},pain:'Expanding GoO trading desk — hiring analyst suggests outgrowing current tools'},status:'pending',pri:'Normal',createdAt:'2026-03-10T14:00:00' },
  { id:'q3',type:'enrichment',title:'Update Vattenfall brief — procurement timeline intel',accName:'Vattenfall Nordic AB',accId:'a1',agent:'Account Enricher',conf:0.76,confBreak:{source_quality:0.85,relevance:0.72,freshness:0.70},reasoning:'LinkedIn post from Lars Eriksson mentions "evaluating 3 vendors for GoO platform" dated March 8.',sources:[{name:'LinkedIn Post',url:'https://linkedin.com/posts/lars-eriksson'}],payload:{field:'whyNow',before:'Budget cycle Q2. Champion Lars actively evaluating.',after:'Budget cycle Q2. Lars confirmed evaluating 3 vendors (LinkedIn post Mar 8). Procurement process active.'},status:'pending',pri:'High',createdAt:'2026-03-10T11:00:00' },
  { id:'q4',type:'task_creation',title:'Schedule follow-up with Torben (Statkraft) via Erik',accName:'Statkraft Markets',accId:'a4',agent:'Pipeline Hygiene',conf:0.68,confBreak:{engagement_decay:0.90,relationship_path:0.55,priority:0.60},reasoning:'No response from Torben in 4 days since intro call. Erik Sandvik (Axpo) provided the referral.',sources:[{name:'Activity Log',url:null},{name:'Contact Graph',url:null}],payload:{task:'Ask Erik Sandvik to nudge Torben Rasmussen re: pilot discussion',due:'2026-03-14',pri:'High'},status:'pending',pri:'Medium',createdAt:'2026-03-11T07:00:00' },
  { id:'q5',type:'outreach_draft',title:'Sequence Step 2 — Enel Green Power follow-up',accName:'Enel Green Power',accId:null,agent:'Outreach Drafter',conf:0.55,confBreak:{relevance:0.70,personalization:0.42,timing:0.52},reasoning:'Low confidence: no response to initial outreach. Contact role unverified.',sources:[{name:'Sequence: Cold Outreach — GoO Pain',url:null}],payload:{to:'Energy Certs Team <certs@enelgreenpower.com>',subject:'Following up — GoO issuance at scale',body:'Hi there,\n\nI reached out last week about Eco-Insight\'s GoO issuance platform.\n\nWould it be helpful to see how other large utilities have automated this workflow?\n\nBest,\nJuuso'},status:'pending',pri:'Low',createdAt:'2026-03-11T08:00:00' },
];

// ── Emails ───────────────────────────────────────
export let emails: Email[] = [
  { id:'e1',subj:'Re: ELcert Module Pricing',from:'erik.sandvik@axpo.com',fromName:'Erik Sandvik',prev:'Thanks for the revised offer. 8.5% works for us. Let\'s finalize in the QBR.',dt:'2026-03-10T16:20:00',unread:true,cls:'positive_reply',clsConf:0.95,linked:true,acc:'Axpo Nordic AS',accId:'a5',agent:'Inbox Classifier' },
  { id:'e2',subj:'RE: SAP Integration — E.ON',from:'kai.mueller@eon.com',fromName:'Kai Mueller',prev:'IT team has follow-up questions on REST endpoints. Can you send API docs?',dt:'2026-03-09T11:40:00',unread:true,cls:'question',clsConf:0.91,linked:true,acc:'E.ON Energy Markets',accId:'a3',agent:'Inbox Classifier' },
  { id:'e3',subj:'Eco-Insight Interest',from:'maria.hoffmann@rwe.com',fromName:'Maria Hoffmann',prev:'We\'d like to learn about GoO issuance capabilities for our European portfolio.',dt:'2026-03-08T09:15:00',unread:false,cls:'positive_reply',clsConf:0.88,linked:false,domain:'rwe.com',acc:'RWE Renewables Europe',accId:'a6',agent:'Inbox Classifier' },
  { id:'e4',subj:'Out of Office: Johan Lindgren',from:'johan.lindgren@vattenfall.com',fromName:'Johan Lindgren',prev:'I am out of office until March 17. For urgent matters contact Lars Eriksson.',dt:'2026-03-09T07:00:00',unread:false,cls:'auto_reply',clsConf:0.99,linked:true,acc:'Vattenfall Nordic AB',accId:'a1',agent:'Inbox Classifier' },
  { id:'e5',subj:'Speaker Invitation — Nordic Energy Summit',from:'events@nordicenergy.org',fromName:'Nordic Energy Events',prev:'We\'d like to invite Eco-Insight to speak at our May summit.',dt:'2026-03-07T14:30:00',unread:false,cls:'meeting_request',clsConf:0.82,linked:false,agent:'Inbox Classifier' },
  { id:'e6',subj:'Partnership Inquiry — Green Certificate Platform',from:'contact@certiverde.io',fromName:'CertiVerde',prev:'We are a new GoO marketplace and would love to discuss API integration.',dt:'2026-03-06T10:00:00',unread:false,cls:'new_domain',clsConf:0.75,linked:false,domain:'certiverde.io',agent:'Inbox Classifier' },
];

// ── Meetings ─────────────────────────────────────
export let meetings: Meeting[] = [
  { id:'m1',title:'E.ON API Integration Review',time:'10:00',dur:'60 min',acc:'E.ON Energy Markets',accId:'a3',who:['Kai Mueller','Thomas Weber'],prep:'ready',date:'2026-03-11' },
  { id:'m2',title:'RWE Discovery Call',time:'14:00',dur:'30 min',acc:'RWE Renewables Europe',accId:'a6',who:['Maria Hoffmann'],prep:'draft',date:'2026-03-20' },
  { id:'m3',title:'Axpo QBR — Q1 Review',time:'09:00',dur:'90 min',acc:'Axpo Nordic AS',accId:'a5',who:['Erik Sandvik','Nick Schoch'],prep:'ready',date:'2026-03-28' },
];

// ── Agent Configs ────────────────────────────────
export const agentConfigs: Record<string, AgentConfig> = {
  signal_hunter: { name:'Signal Hunter',status:'Active · scanning 6 sources daily',desc:'Monitors news, LinkedIn, registries for GoO market signals',params:['Sources: Reuters, Bloomberg, LinkedIn, Montel, AIB, ENTSO-E','Scan frequency: Every 4 hours','Min relevance threshold: 60/100','Auto-dismiss below: 30/100'] },
  lead_qualifier: { name:'Lead Qualifier',status:'Active · FIUAC scoring enabled',desc:'Scores new leads using FIUAC dimensions',params:['Auto-qualify threshold: FIUAC ≥ 70','Auto-disqualify: FIUAC ≤ 25','Route to Queue when: 25 < FIUAC < 70'] },
  account_enricher: { name:'Account Enricher',status:'Active · weekly refresh',desc:'Updates account briefs with new intelligence',params:['Refresh cycle: Weekly','Sources: Signals, email sync, LinkedIn','Min confidence for auto-update: 85%','Below 85%: Route to Queue'] },
  outreach_drafter: { name:'Outreach Drafter',status:'Active · routed to Approval Queue',desc:'Generates personalized outreach using account context',params:['Always route to Queue: Yes','Template style: Consultative','Personalization sources: Pain, WhyNow, Signals','Max sequence length: 4 steps'] },
  pipeline_hygiene: { name:'Pipeline Hygiene',status:'Active · daily health check',desc:'Monitors deal health and flags stale opportunities',params:['Stale threshold: 7 days no activity','Auto-decay: 5 pts/week engagement','Alert when health < 40'] },
  inbox_classifier: { name:'Inbox Classifier',status:'Active · Outlook connected',desc:'Classifies incoming emails by intent',params:['Classification types: Positive, Question, Objection, Meeting, OOO, New Domain','Auto-link by domain: Enabled','New domain detection: Enabled','Min classification confidence: 70%'] },
};
