// Eco-Insight Revenue OS — Seed Data
// Mutable in-memory store. Replace with Prisma/DB in production.
import type { User, Signal, Lead, Account, Opportunity, Task, Goal, Activity, Email, Meeting, QueueItem, AgentConfig } from './types';

// ── Team ─────────────────────────────────────────
export const USERS: User[] = [
  { id: 'u1', name: 'Juuso Kari', initials: 'JK', role: 'Commercial Director', color: 'green' },
  { id: 'u2', name: 'Laura Puranen', initials: 'LP', role: 'CEO', color: 'default' },
  { id: 'u3', name: 'Nick Schoch', initials: 'NS', role: 'COO', color: 'blue' },
];
export const ME = USERS[0];

// ── Signals ──────────────────────────────────────
export let signals: Signal[] = [
  { id:'s1',type:'ppa_announcement',title:'Ørsted signs 15-year corporate PPA with BASF for 186 MW offshore wind',source:'Reuters Energy',sourceUrl:'https://reuters.com/energy/orsted-basf-ppa',detectedAt:'2026-03-11T08:20:00',summary:'BASF will receive GoOs as part of the agreement. Both parties likely need certificate management tooling.',relevance:92,confidence:0.85,reasoning:'Direct GoO involvement in PPA structure. BASF is an industrial buyer with likely manual cert processes.',status:'new',agent:'Signal Hunter' },
  { id:'s2',type:'renewable_target',title:'Iberdrola raises 2030 renewable target to 100 GW globally',source:'Bloomberg Green',sourceUrl:'https://bloomberg.com/iberdrola-target',detectedAt:'2026-03-10T15:40:00',summary:'Expanded target implies massive certificate volume increase across EECS and I-REC schemes.',relevance:85,confidence:0.85,reasoning:'Scale of target creates significant certificate management burden across multiple schemes.',status:'new',agent:'Signal Hunter' },
  { id:'s3',type:'job_posting',title:'Uniper hiring "GoO Trading Analyst" — Düsseldorf',source:'LinkedIn Jobs',sourceUrl:'https://linkedin.com/jobs/uniper-goo',detectedAt:'2026-03-10T12:00:00',summary:'New GoO-specific hire suggests scaling certificate trading operations. Possible greenfield opportunity.',relevance:78,confidence:0.65,reasoning:'GoO-specific role suggests growing operations. New hires often trigger tool evaluation.',status:'new',agent:'Signal Hunter' },
  { id:'s4',type:'market_entry',title:'TotalEnergies launches GoO desk for Scandinavian market',source:'Montel News',sourceUrl:'https://montelnews.com/total-goo',detectedAt:'2026-03-09T09:15:00',summary:'New market entry into Nordics GoO trading. Will need registry connectivity and trading tools from day one.',relevance:88,confidence:0.85,reasoning:'Greenfield GoO desk in our core market. High urgency, no incumbent tooling.',status:'new',agent:'Signal Hunter' },
  { id:'s5',type:'conference',title:'Nordic Energy Certificates Summit — Oslo, May 12-13',source:'Event Detection',sourceUrl:null,detectedAt:'2026-03-08T10:00:00',summary:'Key conference for GoO/ELcert market. Speaking opportunity detected.',relevance:72,confidence:0.65,reasoning:'Networking and lead generation opportunity.',status:'reviewed',agent:'Signal Hunter' },
  { id:'s6',type:'registry_pain',title:'AIB registry downtime causes GoO settlement delays across 12 markets',source:'AIB Alert',sourceUrl:'https://aib-net.org/alerts',detectedAt:'2026-03-07T14:30:00',summary:'Multi-market settlement failure highlights fragility of manual registry workflows.',relevance:90,confidence:0.85,reasoning:'Acute pain event affecting many target accounts. Creates urgency for automation.',status:'new',agent:'Signal Hunter' },
];

// ── Leads ────────────────────────────────────────
export let leads: Lead[] = [
  { id:'l1',company:'BASF SE',domain:'basf.com',source:'Signal',signalId:'s1',type:'Industrial',country:'Germany',region:'DACH',stage:'New',pain:'Likely manual GoO tracking for PPA volumes. No dedicated cert team visible.',moduleFit:['GoO Procurement','Reporting'],scores:{scoreFit:72,scoreIntent:65,scoreUrgency:75,scoreAccess:30,scoreCommercial:80},confidence:0.65,owner:USERS[0],createdAt:'2026-03-11' },
  { id:'l2',company:'Uniper SE',domain:'uniper.com',source:'Signal',signalId:'s3',type:'Utility',country:'Germany',region:'DACH',stage:'Researching',pain:'Expanding GoO trading desk. Currently hiring analyst. Likely outgrowing manual tools.',moduleFit:['GoO Trading','GoO Issuance'],scores:{scoreFit:80,scoreIntent:60,scoreUrgency:70,scoreAccess:35,scoreCommercial:75},confidence:0.65,owner:USERS[0],createdAt:'2026-03-10' },
  { id:'l3',company:'TotalEnergies Trading',domain:'totalenergies.com',source:'Signal',signalId:'s4',type:'Trader',country:'France',region:'Western Europe',stage:'Qualified',pain:'New GoO desk for Nordics — greenfield. Needs full stack from day one.',moduleFit:['GoO Trading','GoO Issuance','Reporting','API Integration'],scores:{scoreFit:90,scoreIntent:85,scoreUrgency:88,scoreAccess:45,scoreCommercial:85},confidence:0.85,owner:USERS[1],createdAt:'2026-03-09' },
  { id:'l4',company:'Enel Green Power',domain:'enelgreenpower.com',source:'Conference',signalId:null,type:'Utility',country:'Italy',region:'Southern Europe',stage:'New',pain:'60 GW renewable capacity globally. Custom internal registry. Scale problem.',moduleFit:['GoO Issuance','Reporting'],scores:{scoreFit:65,scoreIntent:35,scoreUrgency:55,scoreAccess:25,scoreCommercial:90},confidence:0.35,owner:USERS[2],createdAt:'2026-03-05' },
];

// ── Accounts ─────────────────────────────────────
export let accounts: Account[] = [
  { id:'a1',name:'Vattenfall Nordic AB',type:'Utility',country:'Sweden',countryCode:'SE',region:'Nordics',status:'Active',schemes:['GoO','ELcert'],scores:{scoreFit:92,scoreIntent:70,scoreUrgency:82,scoreAccess:75,scoreCommercial:88},ownerId:'u1',owner:USERS[0],pipelineValue:380000,lastActivityAt:'2026-02-19',pain:'Manual GoO reconciliation consuming 3+ FTE. Grexel + Excel workflows cannot scale.',whyNow:'Budget cycle Q2. Champion Lars actively evaluating. Procurement needs 3 vendor quotes.',moduleFit:['GoO Issuance','GoO Trading','Reporting'],aiConfidence:0.85,competitors:'Grexel (incumbent), CMO (shortlisted), Bloomberg TOMS (considered)',contacts:[{id:'c1',name:'Lars Eriksson',title:'Head of GoO Desk',role:'Champion',warmth:'Warm',email:'lars.eriksson@vattenfall.com',phone:'+46 8 739 5000'},{id:'c2',name:'Helena Strand',title:'VP Energy Markets',role:'EconomicBuyer',warmth:'Cold',email:'helena.strand@vattenfall.com'}] },
  { id:'a2',name:'Fortum Power and Heat',type:'Utility',country:'Finland',countryCode:'FI',region:'Nordics',status:'Active',schemes:['GoO','I-REC'],scores:{scoreFit:85,scoreIntent:55,scoreUrgency:75,scoreAccess:60,scoreCommercial:70},ownerId:'u2',owner:USERS[1],pipelineValue:145000,lastActivityAt:'2026-03-09',pain:'Manual I-REC and GoO issuance via Fingrid. 2-person team spending 3 days/month on reconciliation.',whyNow:'CFO budget cycle in Q2. Anna driving but needs executive sponsor.',moduleFit:['I-REC Registry','GoO Issuance'],aiConfidence:0.65,contacts:[{id:'c3',name:'Anna Bergström',title:'Certificate Operations Manager',role:'Champion',warmth:'Warm',email:'anna.bergstrom@fortum.com'},{id:'c4',name:'Annika Virtanen',title:'CFO — Energy Products',role:'EconomicBuyer',warmth:'Cold',email:'annika.virtanen@fortum.com'}] },
  { id:'a3',name:'E.ON Energy Markets',type:'Retailer',country:'Germany',countryCode:'DE',region:'DACH',status:'Active',schemes:['GoO','REGO'],scores:{scoreFit:88,scoreIntent:82,scoreUrgency:88,scoreAccess:70,scoreCommercial:92},ownerId:'u1',owner:USERS[0],pipelineValue:460000,lastActivityAt:'2026-03-08',pain:'SAP + Excel cert management for B2C green tariffs. Evaluating 3 vendors.',whyNow:'Active vendor evaluation. Kai is champion but IT team needs API validation.',moduleFit:['GoO Procurement','Reporting','ERP Integration'],aiConfidence:0.85,contacts:[{id:'c5',name:'Kai Mueller',title:'Head of Energy Markets',role:'Champion',warmth:'Warm',email:'kai.mueller@eon.com'},{id:'c6',name:'Thomas Weber',title:'IT Director',role:'TechnicalBuyer',warmth:'Cold',email:'thomas.weber@eon.com'}] },
  { id:'a4',name:'Statkraft Markets',type:'Trader',country:'Norway',countryCode:'NO',region:'Nordics',status:'Active',schemes:['GoO','ELcert'],scores:{scoreFit:90,scoreIntent:60,scoreUrgency:70,scoreAccess:55,scoreCommercial:85},ownerId:'u1',owner:USERS[0],pipelineValue:290000,lastActivityAt:'2026-03-07',pain:'Bloomberg TOMS + proprietary cert tracking (5 years old). 4 FTE on manual GoO work.',whyNow:'Referral via Axpo. Pilot concept resonated with Torben.',moduleFit:['GoO Trading','GoO Issuance','API Integration'],aiConfidence:0.65,contacts:[{id:'c7',name:'Torben Rasmussen',title:'VP Renewable Trading',role:'EconomicBuyer',warmth:'Cold',email:'torben.rasmussen@statkraft.com'}] },
  { id:'a5',name:'Axpo Nordic AS',type:'Trader',country:'Norway',countryCode:'NO',region:'Nordics',status:'Partner',schemes:['GoO','ELcert','REGO'],scores:{scoreFit:95,scoreIntent:40,scoreUrgency:55,scoreAccess:92,scoreCommercial:80},ownerId:'u1',owner:USERS[0],pipelineValue:95000,lastActivityAt:'2026-03-10',pain:'Live customer. Expanding to ELcert module.',whyNow:'QBR March 28. Expansion pricing negotiation active.',moduleFit:['ELcert Module','API Integration'],aiConfidence:0.90,contacts:[{id:'c8',name:'Erik Sandvik',title:'Head of Certificate Trading',role:'Champion',warmth:'Strong',email:'erik.sandvik@axpo.com'}] },
  { id:'a6',name:'RWE Renewables Europe',type:'Utility',country:'Germany',countryCode:'DE',region:'DACH',status:'Prospect',schemes:['GoO'],scores:{scoreFit:82,scoreIntent:40,scoreUrgency:45,scoreAccess:30,scoreCommercial:90},ownerId:'u2',owner:USERS[1],pipelineValue:320000,lastActivityAt:'2026-03-05',pain:'50 GW renewable capacity. Unknown current tooling.',whyNow:'Discovery call March 20. Maria connected via LinkedIn.',moduleFit:['GoO Issuance','Reporting'],aiConfidence:0.3,contacts:[{id:'c9',name:'Maria Hoffmann',title:'Head of Certificates',role:'Champion',warmth:'Cold',email:'maria.hoffmann@rwe.com'}] },
];

// ── Opportunities ────────────────────────────────
export let opps: Opportunity[] = [
  { id:'o1',name:'Vattenfall GoO Platform',accountId:'a1',accountName:'Vattenfall Nordic AB',stage:'Proposal',amount:380000,probability:65,closeDate:'2026-06-30',owner:USERS[0],health:{healthEngagement:40,healthStakeholders:75,healthCompetitive:60,healthTimeline:50},nextAction:'Follow up on revised GoO volume proposal',nextActionDate:'2026-03-15' },
  { id:'o2',name:'E.ON Germany GoO Procurement',accountId:'a3',accountName:'E.ON Energy Markets',stage:'Evaluation',amount:460000,probability:35,closeDate:'2026-05-31',owner:USERS[0],health:{healthEngagement:65,healthStakeholders:55,healthCompetitive:40,healthTimeline:60},nextAction:'Follow up with Kai on API feasibility',nextActionDate:'2026-03-14' },
  { id:'o3',name:'Statkraft GoO Trading Pilot',accountId:'a4',accountName:'Statkraft Markets',stage:'Evaluation',amount:290000,probability:35,closeDate:'2026-07-31',owner:USERS[0],health:{healthEngagement:30,healthStakeholders:35,healthCompetitive:70,healthTimeline:80},nextAction:'Prepare pilot scope via Erik Sandvik referral',nextActionDate:'2026-03-18' },
  { id:'o4',name:'Fortum I-REC Pilot',accountId:'a2',accountName:'Fortum Power and Heat',stage:'Discovery',amount:145000,probability:20,closeDate:'2026-09-30',owner:USERS[1],health:{healthEngagement:55,healthStakeholders:40,healthCompetitive:80,healthTimeline:70},nextAction:'Send platform overview ahead of call',nextActionDate:'2026-03-12' },
  { id:'o5',name:'E.ON UK REGO Module',accountId:'a3',accountName:'E.ON Next UK',stage:'Proposal',amount:185000,probability:65,closeDate:'2026-04-30',owner:USERS[1],health:{healthEngagement:80,healthStakeholders:70,healthCompetitive:65,healthTimeline:75},nextAction:'Proposal review call with Sarah Hughes',nextActionDate:'2026-03-25' },
  { id:'o6',name:'Axpo ELcert Expansion',accountId:'a5',accountName:'Axpo Nordic AS',stage:'Negotiation',amount:95000,probability:80,closeDate:'2026-03-31',owner:USERS[0],health:{healthEngagement:90,healthStakeholders:85,healthCompetitive:95,healthTimeline:60},nextAction:'Send revised pricing — 8.5% discount',nextActionDate:'2026-03-20' },
  { id:'o7',name:'RWE GoO Issuance',accountId:'a6',accountName:'RWE Renewables Europe',stage:'Discovery',amount:320000,probability:15,closeDate:'2026-12-31',owner:USERS[1],health:{healthEngagement:20,healthStakeholders:25,healthCompetitive:80,healthTimeline:90},nextAction:'Discovery call March 20',nextActionDate:'2026-03-20' },
];

// ── Tasks ────────────────────────────────────────
export let tasks: Task[] = [
  { id:'t1',title:'Follow up Vattenfall — GoO proposal response',accountName:'Vattenfall Nordic AB',accountId:'a1',dueDate:'2026-03-10',owner:USERS[0],assignees:[USERS[0]],priority:'High',status:'Open',source:'Pipeline Hygiene Agent',goalId:'g1',comments:[{author:USERS[1],text:'Lars was responsive last week — try calling directly',createdAt:'2026-03-09T14:00:00'}] },
  { id:'t2',title:'Prepare Statkraft pilot scope document',accountName:'Statkraft Markets',accountId:'a4',dueDate:'2026-03-18',owner:USERS[0],assignees:[USERS[0],USERS[2]],priority:'High',status:'InProgress',source:'Meeting Notes',goalId:'g2',reviewer:USERS[1],comments:[] },
  { id:'t3',title:'Send Fortum platform overview',accountName:'Fortum Power and Heat',accountId:'a2',dueDate:'2026-03-12',owner:USERS[1],assignees:[USERS[1]],priority:'High',status:'Open',source:'Manual',comments:[] },
  { id:'t4',title:'Follow up Kai Mueller — API feasibility',accountName:'E.ON Energy Markets',accountId:'a3',dueDate:'2026-03-08',owner:USERS[0],assignees:[USERS[0]],priority:'High',status:'Open',source:'AI Suggested',comments:[{author:USERS[2],text:'@Juuso — Kai mentioned SSO concern in last call. Address in follow-up.',createdAt:'2026-03-08T09:00:00',mentions:['u1']}] },
  { id:'t5',title:'Send Axpo revised pricing — ELcert',accountName:'Axpo Nordic AS',accountId:'a5',dueDate:'2026-03-20',owner:USERS[0],assignees:[USERS[0]],priority:'Medium',status:'Open',source:'Manual',goalId:'g3',comments:[] },
  { id:'t6',title:'Review 3 new signals',accountName:'',accountId:'',dueDate:'2026-03-11',owner:USERS[0],assignees:[USERS[0],USERS[1]],priority:'Medium',status:'Open',source:'Signal Hunter Agent',comments:[] },
];

// ── Goals ────────────────────────────────────────
export let goals: Goal[] = [
  { id:'g1',title:'Close Vattenfall GoO Platform',accountName:'Vattenfall Nordic AB',accountId:'a1',owner:USERS[0],status:'active' },
  { id:'g2',title:'Launch Statkraft Pilot',accountName:'Statkraft Markets',accountId:'a4',owner:USERS[0],status:'active' },
  { id:'g3',title:'Expand Axpo ELcert',accountName:'Axpo Nordic AS',accountId:'a5',owner:USERS[0],status:'active' },
];

// ── Activities ───────────────────────────────────
export let activities: Activity[] = [
  { id:'x1',type:'Email',createdAt:'2026-03-10T09:14:00',accountId:'a5',accountName:'Axpo Nordic AS',summary:'ELcert module pricing — revised offer sent',detail:'Sent 8.5% multi-module discount proposal. Awaiting Erik\'s sign-off.',author:USERS[0],source:'Outlook Sync' },
  { id:'x2',type:'Meeting',createdAt:'2026-03-09T14:00:00',accountId:'a2',accountName:'Fortum Power and Heat',summary:'Discovery call — Fortum I-REC registry needs',detail:'Anna confirmed interest. Key concern: CFO approval needed.',author:USERS[1],source:'Calendar Sync' },
  { id:'x3',type:'Email',createdAt:'2026-03-08T16:30:00',accountId:'a3',accountName:'E.ON Energy Markets',summary:'API integration feasibility — follow-up sent',detail:'Sent SAP connector documentation. Awaiting IT team review.',author:USERS[0],source:'Outlook Sync' },
  { id:'x4',type:'Meeting',createdAt:'2026-03-07T10:00:00',accountId:'a4',accountName:'Statkraft Markets',summary:'Intro call via Erik Sandvik referral',detail:'Good intro. Torben aware of Eco-Insight via Axpo. Pilot concept resonated.',author:USERS[0],source:'Calendar Sync' },
  { id:'x5',type:'Email',createdAt:'2026-02-28T11:00:00',accountId:'a3',accountName:'E.ON Energy Markets',summary:'Commercial proposal sent — E.ON Germany',detail:'Full proposal submitted. €460K ARR, 3-year term.',author:USERS[0],source:'Outlook Sync' },
  { id:'x6',type:'Note',createdAt:'2026-02-19T09:00:00',accountId:'a1',accountName:'Vattenfall Nordic AB',summary:'Revised GoO volume proposal sent',detail:'Updated commercial terms with volume thresholds. No response yet.',author:USERS[0],source:'Manual' },
];

// ── Queue ────────────────────────────────────────
export let queue: QueueItem[] = [
  { id:'q1',type:'outreach_draft',title:'Cold outreach to BASF SE — GoO Procurement',accountName:'BASF SE',accountId:null,agent:'Outreach Drafter',confidence:0.82,confidenceBreakdown:{relevance:0.92,personalization:0.74,timing:0.81},reasoning:'BASF appeared in PPA signal with Ørsted. Industrial buyer profile matches ICP. No prior contact — cold outreach via LinkedIn-sourced contact.',sources:[{name:'Reuters Energy',url:'https://reuters.com/energy/orsted-basf-ppa'},{name:'LinkedIn',url:'https://linkedin.com/in/basf-energy'}],payload:{to:'Michael Braun <m.braun@basf.com>',subject:'Eco-Insight — GoO certificate management for BASF',body:'Hi Michael,\n\nI noticed BASF recently signed a 186 MW offshore wind PPA with Ørsted. Agreements of this scale typically involve significant GoO certificate volumes.\n\nWould you be open to a brief conversation about how we help companies like yours automate GoO management?\n\nBest,\nJuuso Kari'},status:'pending',priority:'Normal',createdAt:'2026-03-11T09:30:00' },
  { id:'q2',type:'lead_qualification',title:'Qualify Uniper SE as GoO Trading lead',accountName:'Uniper SE',accountId:null,agent:'Lead Qualifier',confidence:0.71,confidenceBreakdown:{icp_fit:0.80,intent:0.65,entity_match:0.68},reasoning:'Uniper hiring GoO Trading Analyst. Signal confidence is medium because job posting doesn\'t confirm tool evaluation.',sources:[{name:'LinkedIn Jobs',url:'https://linkedin.com/jobs/uniper-goo'}],payload:{company:'Uniper SE',type:'Utility',country:'Germany',stage:'Researching',scores:{scoreFit:80,scoreIntent:60,scoreUrgency:70,scoreAccess:35,scoreCommercial:75},pain:'Expanding GoO trading desk — hiring analyst suggests outgrowing current tools'},status:'pending',priority:'Normal',createdAt:'2026-03-10T14:00:00' },
  { id:'q3',type:'enrichment',title:'Update Vattenfall brief — procurement timeline intel',accountName:'Vattenfall Nordic AB',accountId:'a1',agent:'Account Enricher',confidence:0.76,confidenceBreakdown:{source_quality:0.85,relevance:0.72,freshness:0.70},reasoning:'LinkedIn post from Lars Eriksson mentions "evaluating 3 vendors for GoO platform" dated March 8.',sources:[{name:'LinkedIn Post',url:'https://linkedin.com/posts/lars-eriksson'}],payload:{field:'whyNow',before:'Budget cycle Q2. Champion Lars actively evaluating.',after:'Budget cycle Q2. Lars confirmed evaluating 3 vendors (LinkedIn post Mar 8). Procurement process active.'},status:'pending',priority:'High',createdAt:'2026-03-10T11:00:00' },
  { id:'q4',type:'task_creation',title:'Schedule follow-up with Torben (Statkraft) via Erik',accountName:'Statkraft Markets',accountId:'a4',agent:'Pipeline Hygiene',confidence:0.68,confidenceBreakdown:{engagement_decay:0.90,relationship_path:0.55,priority:0.60},reasoning:'No response from Torben in 4 days since intro call. Erik Sandvik (Axpo) provided the referral.',sources:[{name:'Activity Log',url:null},{name:'Contact Graph',url:null}],payload:{task:'Ask Erik Sandvik to nudge Torben Rasmussen re: pilot discussion',due:'2026-03-14',pri:'High'},status:'pending',priority:'Medium',createdAt:'2026-03-11T07:00:00' },
  { id:'q5',type:'outreach_draft',title:'Sequence Step 2 — Enel Green Power follow-up',accountName:'Enel Green Power',accountId:null,agent:'Outreach Drafter',confidence:0.55,confidenceBreakdown:{relevance:0.70,personalization:0.42,timing:0.52},reasoning:'Low confidence: no response to initial outreach. Contact role unverified.',sources:[{name:'Sequence: Cold Outreach — GoO Pain',url:null}],payload:{to:'Energy Certs Team <certs@enelgreenpower.com>',subject:'Following up — GoO issuance at scale',body:'Hi there,\n\nI reached out last week about Eco-Insight\'s GoO issuance platform.\n\nWould it be helpful to see how other large utilities have automated this workflow?\n\nBest,\nJuuso'},status:'pending',priority:'Low',createdAt:'2026-03-11T08:00:00' },
];

// ── Emails ───────────────────────────────────────
export let emails: Email[] = [
  { id:'e1',subject:'Re: ELcert Module Pricing',fromEmail:'erik.sandvik@axpo.com',fromName:'Erik Sandvik',preview:'Thanks for the revised offer. 8.5% works for us. Let\'s finalize in the QBR.',receivedAt:'2026-03-10T16:20:00',isUnread:true,classification:'positive_reply',classificationConf:0.95,isLinked:true,accountName:'Axpo Nordic AS',accountId:'a5',classifierAgent:'Inbox Classifier' },
  { id:'e2',subject:'RE: SAP Integration — E.ON',fromEmail:'kai.mueller@eon.com',fromName:'Kai Mueller',preview:'IT team has follow-up questions on REST endpoints. Can you send API docs?',receivedAt:'2026-03-09T11:40:00',isUnread:true,classification:'question',classificationConf:0.91,isLinked:true,accountName:'E.ON Energy Markets',accountId:'a3',classifierAgent:'Inbox Classifier' },
  { id:'e3',subject:'Eco-Insight Interest',fromEmail:'maria.hoffmann@rwe.com',fromName:'Maria Hoffmann',preview:'We\'d like to learn about GoO issuance capabilities for our European portfolio.',receivedAt:'2026-03-08T09:15:00',isUnread:false,classification:'positive_reply',classificationConf:0.88,isLinked:false,domain:'rwe.com',accountName:'RWE Renewables Europe',accountId:'a6',classifierAgent:'Inbox Classifier' },
  { id:'e4',subject:'Out of Office: Johan Lindgren',fromEmail:'johan.lindgren@vattenfall.com',fromName:'Johan Lindgren',preview:'I am out of office until March 17. For urgent matters contact Lars Eriksson.',receivedAt:'2026-03-09T07:00:00',isUnread:false,classification:'auto_reply',classificationConf:0.99,isLinked:true,accountName:'Vattenfall Nordic AB',accountId:'a1',classifierAgent:'Inbox Classifier' },
  { id:'e5',subject:'Speaker Invitation — Nordic Energy Summit',fromEmail:'events@nordicenergy.org',fromName:'Nordic Energy Events',preview:'We\'d like to invite Eco-Insight to speak at our May summit.',receivedAt:'2026-03-07T14:30:00',isUnread:false,classification:'meeting_request',classificationConf:0.82,isLinked:false,classifierAgent:'Inbox Classifier' },
  { id:'e6',subject:'Partnership Inquiry — Green Certificate Platform',fromEmail:'contact@certiverde.io',fromName:'CertiVerde',preview:'We are a new GoO marketplace and would love to discuss API integration.',receivedAt:'2026-03-06T10:00:00',isUnread:false,classification:'new_domain',classificationConf:0.75,isLinked:false,domain:'certiverde.io',classifierAgent:'Inbox Classifier' },
];

// ── Meetings ─────────────────────────────────────
export let meetings: Meeting[] = [
  { id:'m1',title:'E.ON API Integration Review',startTime:'10:00',duration:'60 min',accountName:'E.ON Energy Markets',accountId:'a3',attendees:['Kai Mueller','Thomas Weber'],prepStatus:'ready',date:'2026-03-11' },
  { id:'m2',title:'RWE Discovery Call',startTime:'14:00',duration:'30 min',accountName:'RWE Renewables Europe',accountId:'a6',attendees:['Maria Hoffmann'],prepStatus:'draft',date:'2026-03-20' },
  { id:'m3',title:'Axpo QBR — Q1 Review',startTime:'09:00',duration:'90 min',accountName:'Axpo Nordic AS',accountId:'a5',attendees:['Erik Sandvik','Nick Schoch'],prepStatus:'ready',date:'2026-03-28' },
];

// ── Agent Configs ────────────────────────────────
export const agentConfigs: Record<string, AgentConfig> = {
  signal_hunter: { name:'Signal Hunter',status:'Active · scanning 6 sources daily',desc:'Monitors news, LinkedIn, registries for GoO market signals',params:['Sources: Reuters, Bloomberg, LinkedIn, Montel, AIB, ENTSO-E','Scan frequency: Every 4 hours','Min relevance threshold: 60/100','Auto-dismiss below: 30/100'] },
  lead_qualifier: { name:'Lead Qualifier',status:'Active · FIUAC scoring enabled',desc:'Scores new leads using FIUAC dimensions',params:['Auto-qualify threshold: FIUAC ≥ 70','Auto-disqualify: FIUAC ≤ 25','Route to Queue when: 25 < FIUAC < 70'] },
  account_enricher: { name:'Account Enricher',status:'Active · weekly refresh',desc:'Updates account briefs with new intelligence',params:['Refresh cycle: Weekly','Sources: Signals, email sync, LinkedIn','Min confidence for auto-update: 85%','Below 85%: Route to Queue'] },
  outreach_drafter: { name:'Outreach Drafter',status:'Active · routed to Approval Queue',desc:'Generates personalized outreach using account context',params:['Always route to Queue: Yes','Template style: Consultative','Personalization sources: Pain, WhyNow, Signals','Max sequence length: 4 steps'] },
  pipeline_hygiene: { name:'Pipeline Hygiene',status:'Active · daily health check',desc:'Monitors deal health and flags stale opportunities',params:['Stale threshold: 7 days no activity','Auto-decay: 5 pts/week engagement','Alert when health < 40'] },
  inbox_classifier: { name:'Inbox Classifier',status:'Active · Outlook connected',desc:'Classifies incoming emails by intent',params:['Classification types: Positive, Question, Objection, Meeting, OOO, New Domain','Auto-link by domain: Enabled','New domain detection: Enabled','Min classification confidence: 70%'] },
};
